### ISSUE TITLE
Execute code in prelim markdowns when knitting to a latex document

### ISSUE THREAD

**Issue by christianholland** [ismayc/thesisdown#144]
Hi,
given I have a separate `preface.Rmd` document in the `prelims` folder with only a single line of R code as content:

```r
plot(mtcars)
```

Accordingly I have added to `index.Rmd`
```
preface: '`r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "preface.Rmd")), collapse = "\n  ")`'
```

 so that the `preface.Rmd` is included in the final pdf. However the `readLines()` function doesn't recognise R code and treats everything a usual characters showing only "{r} plot(mtcars)", however, written in a different font (?).

Is there a way to execute the code within `preface.Rmd`?

Thanks,
Christian

**Comment by ismayc** [comment]
Hmm, I'm gonna have to think on this a bit. We are gonna likely have to do some hacking since Preface appears before \mainmatter in `template.tex` and you can't really define a chunk for `preface` like what I do for the non-PDF prelim inclusion on [line 106](https://github.com/ismayc/thesisdown/blob/b63d9f60f4f673bf9e272ede02e4a85abf27b422/inst/rstudio/templates/project/resources/index.Rmd#L106) of `index.Rmd`. I don't think I ever planned for someone to have calculations in the preliminary content :-/

**Comment by ismayc** [comment]
It looks like the best I can do is to add the following lines to just above the line 106 I referred to in the previous comment:

![Screen Shot 2021-03-20 at 11 30 37 AM](https://user-images.githubusercontent.com/9215614/111881849-b8d0d100-896f-11eb-94e1-e4701ac87d5a.png)

and comment out the `preface` line in the YAML. You'll have to do something similar for the preliminary content like `acknowledgements` if you'd like them to appear after the Preface.

**Comment by christianholland** [comment]
This workaround works perfectly, thanks a lot
