### ISSUE TITLE
Adapting thesisdown to new institution

### ISSUE THREAD

**Issue by arnold-c** [ismayc/thesisdown#156]
As with #74, I am trying to adapt `{thesisdown}` to my institution (Penn State University), and have very limited experience with LaTeX, especially not templates, hence the incentive to use Rmd. I have converted all the standard files as other forks have, but the `.tex` and `.cls` files are clearly different enough that I can't get by with a straight replacement. If you have time, would you mind giving me a hand in figuring out what's going on?

At the moment, I'm getting the following error code when trying to knit to pdf.

```
! Paragraph ended before \@iinput was complete.
<to be read again> 
                   \par 
l.323 Second paragraph of abstract starts here.}

Error: LaTeX failed to compile thesis.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See thesis.log for more info.
Execution halted
```

I have created a fork that can be found [here](https://github.com/arnold-c/liondown).

Thanks for your help

**Comment by ismayc** [comment]
Hi there. I'm hoping to look into this further later this week or early next week if possible.

**Comment by ismayc** [comment]
Sorry for the delay here. It's still on my to-do list, but I haven't had a chance to look at it yet. I might recommend just working with the standard Reed template and in R Markdown files until I can assist with the LaTeX.

**Comment by KDrakoulaki** [comment]
Hi! I'm replying to this because, similar to OP I am trying to adapt thesisdown to my institution's requirements, but I'm not well versed in LaTeX. Please if this is not appropriate I will open another issue (and thanks for all your hard work, this has been a life saver!). I have tried looking at other adaptations' ideas with regard to the template.tex file and the changes in the index.Rmd yaml info, but I can't seem to get it right. Fortunately, it's just the first page and the colophon that needs to be changed. 

I tried to 'translate' the requirements of the first page into this (i.e. how I imagine that LaTeX commands work somehow - but I imagine it depends on the documentclass?):

`Title page
University
Faculty
Department

Title

Author

Doctoral dissertation

Supervisor

Supervisory committee
name 1
name 2
name 3

Examination committee
name 1
name 2
name 3
name 4
name 5
name 6
name 7

location
date

image file with funding body logo at the bottom 



Colophon
copyright statement

License text `

I'm really sorry if this is something silly or beginner level, but I didn't know where else to ask! Thanks in advance.

**Comment by ismayc** [comment]
Hi there! I might be able to help with this. Could you share an image of what a sample page looks like?

**Comment by KDrakoulaki** [comment]
Hi, thanks for the response! The sample I was given is in Greek (as I'm studying in a Greek university)...  Also, its layout is really bad, so not sure if it's going to be helpful. There are two alternatives, one without the committees and one with the committees. So the information I've put above is identical to what is written in Greek. I'm writing my thesis in English so I don't need to worry about a Greek first page. Also, apart from the sample, my funding body requires me to put its logo at the bottom of the first page (do you need it attached?). I hope this makes sense!

![image](https://user-images.githubusercontent.com/39005148/124728804-8c3dc680-df18-11eb-8fb5-d7b19985f82b.png)


![image](https://user-images.githubusercontent.com/39005148/124728849-96f85b80-df18-11eb-8a80-3f2e2233b558.png)

**Comment by ismayc** [comment]
Thanks! That's helpful. It's been a bit since I've dug into the template.tex file or the reedthesis.cls to identify the changes needed to convert it over to work with bookdown/thesisdown. I'm going to work with my former colleagues to get their LaTeX template files so I can better assist others with the changes needed.

**Comment by ismayc** [comment]
Here are the current Reed College LaTeX files (for either Windows or Mac).

[LaTeX_Thesis_mac.zip](https://github.com/ismayc/thesisdown/files/6835191/LaTeX_Thesis_mac.zip)
[LaTeX_Thesis_windows.zip](https://github.com/ismayc/thesisdown/files/6835192/LaTeX_Thesis_windows.zip)

These should be similar to what I originally adapted with the `reedthesis.cls` and `template.tex` files. Hopefully that gives you some further insight to see the changes I made there that you can make with your institution.

**Comment by ailich** [comment]
Hi, I'm also trying to adapt this to my institution (University of South Florida). I've been trying to adapt this repository by creating an Rmarkdown template based on some unofficial USF Latex document class and template files which are available from http://shell.cas.usf.edu/~saito/grad/. After playing with that for a while I was able to get a package that has a custom template (https://github.com/ailich/bulldown) and can be installed with `remotes::install_github("ailich/bulldown"`. The document will knit, but if I add any headers to the child documents (e.g. # Chapter 1) I get the error ! "Undefined control sequence. l.49 \hypertarget". Any chance you know what's going on here? I've included a [text file](https://github.com/ailich/bulldown/blob/master/Creating%20R%20Markdown%20Template%20for%20USF%20Dissertation.txt) which lists the steps I took to create this R package/template and the edits I had to make to various files. I'm not 100% sure what I'm doing in all the steps though (e.g. edits to template.tex and including the functions for knitting from thesisdown) so I might be making some mistakes in the setup. Any help would be greatly appreciated.

**Comment by ismayc** [comment]
I just don't have the availability to support further with this at this time. You might try contacting one of the people that have adapted this to their institution (e.g., [huskydown](https://github.com/benmarwick/huskydown/issues)) for troubleshooting.

**Comment by ailich** [comment]
@ismayc, thank you. I will see if they have any advice.
