### ISSUE TITLE
apostrophe ’ in the abstract file is rendered as â€™ 

### ISSUE THREAD

**Issue by sisbra** [ismayc/thesisdown#187]
**Describe the bug**
Apostrophe ’ in the abstract file is rendered as â€™ once knitted. This only happens in the abstract (in the folder "prelims") and not in the chapters.

**Comment by ismayc** [comment]
Hi there. The apostrophe is read differently because the abstract has to be read in differently as a front matter item. Maybe replacing the apostrophe with its corresponding ASCII code can work. There were some updates added recently by another user that may also fix this. I'm not sure when you started working on this, so you might want to check the commit history to see if those changes will help you.

**Comment by sisbra** [comment]
the change I found in the commit history worked! thanks a lot!
