### ISSUE TITLE
Derivative files in package?

### ISSUE THREAD

**Issue by zkamvar** [ismayc/thesisdown#2]
I was poking around and noticed that there are quite a lot of derivative files in this package. I'm wondering which files exactly are derivative (for example, it's clear that [skeleton/_book/](https://github.com/ismayc/thesisdown/tree/master/inst/rmarkdown/templates/thesis/skeleton/_book) is a derivative, but others are not so clear.)

Otherwise, this is a fantastic idea. I plan on using this framework using the style guide from Oregon State University for my own dissertation.

**Comment by ismayc** [comment]
Ah, I had been meaning to put the `_book` and `_bookdown_files` folders into the `.gitignore`.  Thanks for the reminder!  Here is a breakdown of what is in each of the folders and whether or not they are needed.  As a general rule, the folders (`bib`, `csl`, `data`, and `figure`) are not needed.  They are there only for organization.

`bib` contains the bibliography file information created using Bibtex/Zotero.

`csl` contains the Citation Style Language file (Many different available at https://www.zotero.org/styles)

`data` contains an example dataset to work with in CSV format

`figure` contains a couple images that are alluded to in the template.

The `00--prelim.Rmd` and `00-abstract.Rmd` files correspond to the preliminary content/preamble of the document.  They are named so that `00--prelim.Rmd` comes before `00-abstract.Rmd` alphabetically.

The `01-chap1.Rmd`, `02-chap2.Rmd`, `03-chap3.Rmd`, `04-conclusion.Rmd`, and `99-references.Rmd` files are there really only as examples.  I encourage you to name the references file with a high number so that it is ensured to go last.

The `_bookdown.yml` file contains some text that can be tweaked as you see fit.  As of version 0.0.2, you'll need to comment out the `rmd_files` line if you are building a non-LaTeX/PDF version. 

The `chemarr.sty` file can likely be deleted.  There are some Chemistry students at Reed that need that package so I included it here.

`reedthesis.cls` and `template.tex` correspond to the LaTeX template file used by Reed students.  This can be tweaked if your institution uses a different template file.

The `skeleton.Rmd` file is the driving file and it is required to be named `skeleton.Rmd` for R Markdown to know that this is a template file.  As of version 0.0.2, you'll need to name your file `index` when you create a New R Markdown From Template so that it works to build a webpage as well.

Feel free to let me know if you have any other questions.  I have a feeling I might need to put together a bookdown book to explain a lot of these things, but I tried to leave lots of markdown comments throughout the document explaining what is going on.

Please do keep me posted on how this works for you at Oregon State.  If you are ever up in Portland, I'd love to chat.
