### ISSUE TITLE
citation and text styling within fig.cap 

### ISSUE THREAD

**Issue by tkaraouzene** [ismayc/thesisdown#27]
Hi @ismayc, 

I have an issue when I insert citation and/or text styling within a fig.cap.
They are not recognized and they are displayed as basic text when I ask for pdf output (it works fine for HTML and Word output).

I saw your issue in [boodown](https://github.com/rstudio/bookdown/) repo [issues #203](https://github.com/rstudio/bookdown/issues/203) but even after having re-install my latex distribution it still doesn't work for me (my OS is Linux CentOS 7).  

Thanks again for your package and I attach a screenshot to explain my issue if it wasn't clear.

![example](https://user-images.githubusercontent.com/20064077/27577524-4e6526d4-5b21-11e7-9e5b-3f1a43ddcb06.png)

**Comment by ismayc** [comment]
Can you try adding this image and its reference to the bookdown-demo repo and see if the issue persists there as well?

**Comment by tkaraouzene** [comment]
Hi, @ismayc,

This is what I obtain when I use the bookdown-demo repo and so as you can see the issue does **not** persist. 

![myfig](https://user-images.githubusercontent.com/20064077/27598439-c8ea08b8-5b65-11e7-97b2-66989bdab6fc.png)

Thanks for your attention,

**Comment by ismayc** [comment]
I'm currently on vacation so it will take me a couple weeks to get back you on this.  In the time being, there must be something different in how I specify `thesis_pdf` for `thesisdown` that is not working for you.  I recommend you use `bookdown::pdf_book` and set the options manually to fit your needs.  If you figure out what code is causing the problem in `thesis_pdf`, please let me know.

**Comment by tkaraouzene** [comment]
Ok, no problem I check that and I let you know if I find something.
Have good holidays,
Thomas

**Comment by keurcien** [comment]
Hi,

I had this problem as well and figured it is actually related to bookdown. But since a neat way using text references can already be found on [bookdown](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references), I thought it'd make more sense to pin it here:

To have "*from* (Angel, 2000)" as a figure caption, a portable way (gitbook/pdf at least) to do this is to use a text reference: 

```
(ref:foo) [@angel2000]
```
and set `fig.cap='(ref:foo)'`

If you are interested in knowing what issues may arise if you use Markdown styling within fig.cap, here's what I have found out on my laptop :

1. If the output is generated from R (e.g using plot or ggplot): 

- If option `fig.align` is not used, citation and Markdown formatting within the figure caption work well. And when looking at the .tex output, you actually see that `\centering` is used, meaning that the figure will be centered by default, and the caption will be formatted as desired.

` ```{r march3plot, fig.height=3, fig.width=6, fig.cap='*from* [@angel2000]'}`
`flights %>% filter(month == 3, day == 3) %>%`
`ggplot(aes(x = dep_time, y = arr_delay)) + geom_point()`
` ``` `

- However, if option `fig.align` is set (to whatever value you feel like), whether by changing the options in the chunk itself or using `knitr::opts_chunk$set`, neither citation nor Markdown formatting will work. 

2. If the output involves `knitr::include_graphics` :

- None of the above works.

Anyway, thanks again for the package !

**Comment by ismayc** [comment]
Cool!  Thanks, @keurcien!

**Comment by tkaraouzene** [comment]
Nice work ! 
Thank you

**Comment by mavogel** [comment]
@keurcien thank you for your investigation! Did you find another way to include a graphic in `bookdown` without using `knitr::include_graphics`? `fig.align` is can word around but not the other one.
