### ISSUE TITLE
Mirrored margins in pdf output

### ISSUE THREAD

**Issue by Programming-Skills** [ismayc/thesisdown#95]
I seem to have mirrored margins in my pdf output. i.e one page is slightly aligned left and the next page is slightly aligned right. I guess this for those who want to bind their thesis. Is there any way to justify the text output so it's all centered? 

![Capture](https://user-images.githubusercontent.com/19156006/84488927-d3677280-ac98-11ea-882e-1d09262c100d.JPG)

**Comment by ismayc** [comment]
Hi there! If you are using the reedthesis.cls file in the template, you can change [this line](https://github.com/ismayc/thesisdown/blob/b1fb5b503009b94389663d8ca9f19e9b1b0458f4/inst/rmarkdown/templates/thesis/skeleton/template.tex#L27) of **template.tex** to be

```
\documentclass[12pt,oneside]{reedthesis}
```

instead. 

To eliminate a couple warnings that will exist because there are references to left/right and even/odd pages that go along with `twoside`, you'll also need to tweak the lines of code just below `\AtBeginDocument{` in the **reedthesis.cls** file to be 

```
\fancyhead{\thepage}
\fancyhead{\slshape \nouppercase \leftmark}
```

instead of

```
\fancyhead[LE,RO]{\thepage}
\fancyhead[RE]{\slshape \nouppercase \leftmark} 
\fancyhead[LO]{\slshape \nouppercase \rightmark} 
```

Hopefully that does the trick for you!

**Comment by ismayc** [comment]
I'm going to close this issue now, but feel free to reopen if you need related help on this topic.

**Comment by Programming-Skills** [comment]
Many thanks! I will give it a try!
